performance improvements for jaguar

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MADNESS_MMM_VERSION MADNESS_BUILDID MADNESS_MAJOR_VERSION MADNESS_MINOR_VERSION MADNESS_MICRO_VERSION MADNESS_SO_VERSION madincludedir BUILDID MADNESS_VERSION ARFLAGS LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC CXXCPP CPP AR PERL DOXYGEN LD DOT DOT_PATH HAVE_DOT PDFLATEX HAVE_PDFLATEX EXTRAINCLUDE EXTRADEFINES LIBDIRS OBJSUF LIBSUF CXXDEPENDSUF CXXDEPENDFLAGS CCDEPENDSUF CCDEPENDFLAGS EGREP F77_SYMBOL BLAS LAPACK MPI_H_BREAKS_CXX HAVE_MPI HAVE_MPI_CXX_BINDINGS HAVE_PTHREADS TMPLINST TMPLREPO TMPLINLIB ECHO ac_ct_AR STRIP ac_ct_STRIP F77 FFLAGS ac_ct_F77 LIBTOOL ENABLESHARED LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MADNESS_MMM_VERSION MADNESS_BUILDID MADNESS_MAJOR_VERSION MADNESS_MINOR_VERSION MADNESS_MICRO_VERSION MADNESS_SO_VERSION madincludedir BUILDID MADNESS_VERSION ARFLAGS LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC CXXCPP CPP AR PERL DOXYGEN LD DOT DOT_PATH HAVE_DOT ASTYLE ASTYLEFLAGS PDFLATEX HAVE_PDFLATEX EXTRAINCLUDE EXTRADEFINES LIBDIRS OBJSUF LIBSUF CXXDEPENDSUF CXXDEPENDFLAGS CCDEPENDSUF CCDEPENDFLAGS EGREP F77_SYMBOL BLAS LAPACK MPI_H_BREAKS_CXX HAVE_MPI HAVE_MPI_CXX_BINDINGS HAVE_PTHREADS TMPLINST TMPLREPO TMPLINLIB ECHO ac_ct_AR STRIP ac_ct_STRIP F77 FFLAGS ac_ct_F77 LIBTOOL ENABLESHARED LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1053,6 +1053,8 @@ Optional Packages:
   --with-template         Specifies template instantation model.
   --with-libs             Specifies libraries (-llib1 -llib2).
   --with-libdirs          Specifies library directories (-Ldir1 -Ldir2).
+  --with-astyle-flags         Flags for the pretty printer astyle.
+  --with-fortran-integer    Equivalent C type to Fortran integer (default is long)
   --with-f77symbol        FORTRAN77 symbol convention. Allowed values are:
                             lc  (lower-case)
                             lcu (lower-case with underscore; default, if not given)
@@ -4076,6 +4078,53 @@ fi
 
 
 
+# Extract the first word of "astyle", so it can be a program name with args.
+set dummy astyle; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_ASTYLE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ASTYLE"; then
+  ac_cv_prog_ASTYLE="$ASTYLE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ASTYLE="astyle"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+ASTYLE=$ac_cv_prog_ASTYLE
+if test -n "$ASTYLE"; then
+  echo "$as_me:$LINENO: result: $ASTYLE" >&5
+echo "${ECHO_T}$ASTYLE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+ASTYLEFLAGS="--style=kr -N"
+
+# Check whether --with-astyle-flags or --without-astyle-flags was given.
+if test "${with_astyle_flags+set}" = set; then
+  withval="$with_astyle_flags"
+  ASTYLEFLAGS=$withval
+
+fi;
+
+
+
+
 # Extract the first word of "pdflatex", so it can be a program name with args.
 set dummy pdflatex; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -5360,6 +5409,19 @@ fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 
+
+
+
+
+# Check whether --with-fortran_integer or --without-fortran_integer was given.
+if test "${with_fortran_integer+set}" = set; then
+  withval="$with_fortran_integer"
+  EXTRADEFINES="$EXTRADEFINES -DMADNESS_FORINT=$withval"
+
+fi;
+cat >>confdefs.h <<_ACEOF
+#define MADNESS_FORTRAN_INTEGER_TYPE "$MADNESS_FORTRAN_INTEGER_TYPE"
+_ACEOF
 
 
 
@@ -6667,7 +6729,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-int argc = 0; char** argv = 0; MPI_Init(&argc,&argv); MPI_Finalize();
+int argc = 0; char** argv = 0; MPI::Init(argc,argv); MPI::Finalize();
 
   ;
   return 0;
@@ -7126,6 +7188,11 @@ _ACEOF
     fi
   fi
 
+fi
+
+if test X"$HAVE_MPI" = X; then
+  { echo "$as_me:$LINENO: WARNING: !! MPI not found ... configure proceeding but MADNESS cannot be compiled without MPI headers+library." >&5
+echo "$as_me: WARNING: !! MPI not found ... configure proceeding but MADNESS cannot be compiled without MPI headers+library." >&2;}
 fi
 
 
@@ -7782,7 +7849,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7785 "configure"' > conftest.$ac_ext
+  echo '#line 7852 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8423,7 +8490,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:8426:" \
+echo "$as_me:8493:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -9525,11 +9592,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9528: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9595: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9532: \$? = $ac_status" >&5
+   echo "$as_me:9599: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9787,11 +9854,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9790: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9857: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9794: \$? = $ac_status" >&5
+   echo "$as_me:9861: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9849,11 +9916,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9852: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9919: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9856: \$? = $ac_status" >&5
+   echo "$as_me:9923: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12097,7 +12164,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12100 "configure"
+#line 12167 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12195,7 +12262,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12198 "configure"
+#line 12265 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14454,11 +14521,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14457: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14524: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14461: \$? = $ac_status" >&5
+   echo "$as_me:14528: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14516,11 +14583,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14519: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14586: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14523: \$? = $ac_status" >&5
+   echo "$as_me:14590: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15893,7 +15960,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15896 "configure"
+#line 15963 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15991,7 +16058,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15994 "configure"
+#line 16061 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16876,11 +16943,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16879: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16946: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16883: \$? = $ac_status" >&5
+   echo "$as_me:16950: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16938,11 +17005,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16941: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17008: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16945: \$? = $ac_status" >&5
+   echo "$as_me:17012: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19072,11 +19139,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19075: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19142: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19079: \$? = $ac_status" >&5
+   echo "$as_me:19146: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19334,11 +19401,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19337: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19341: \$? = $ac_status" >&5
+   echo "$as_me:19408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19396,11 +19463,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19399: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19466: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19403: \$? = $ac_status" >&5
+   echo "$as_me:19470: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21644,7 +21711,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21647 "configure"
+#line 21714 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21742,7 +21809,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21745 "configure"
+#line 21812 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23444,6 +23511,8 @@ s,@LD@,$LD,;t t
 s,@DOT@,$DOT,;t t
 s,@DOT_PATH@,$DOT_PATH,;t t
 s,@HAVE_DOT@,$HAVE_DOT,;t t
+s,@ASTYLE@,$ASTYLE,;t t
+s,@ASTYLEFLAGS@,$ASTYLEFLAGS,;t t
 s,@PDFLATEX@,$PDFLATEX,;t t
 s,@HAVE_PDFLATEX@,$HAVE_PDFLATEX,;t t
 s,@EXTRAINCLUDE@,$EXTRAINCLUDE,;t t
